### ISSUE TITLE
Incorporate Photo Gallery into site

### ISSUE THREAD

**Issue by SiamKreative** [SiamKreative/website#44]
Even though the target audience is mainly recruiters and business professionals, I still want to keep a personal touch.

Therefore, I want to have https://photos.siamkreative.com/ built into my Gridsome website.

## Todo
- [ ] Imagekit for image CDN ([example URL](https://ik.imagekit.io/siamkreative/tr:w-1200,h-800,c-force/DSC07055_qhwr6Xvr3.jpg)).
- [ ] Gridsome [import data from API](https://gridsome.org/docs/fetching-data/#import-from-apis) (need basic auth so .env shall be referenced). Endpoint URL is `https://api.imagekit.io/v1/files` and requires basic auth with:
     - Username: private key
     - Password: empty string
- [ ] Frontend CSS grid https://medium.com/@reneecruz/create-a-masonry-image-gallery-using-css-grid-9b3909794f5e
